version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: C:\Users\Developer\Documents\postman\postman\postman_collection.json
          environment: C:\Users\Developer\Documents\postman\postman\newman\New Environment.postman_environment.json